FROM openjdk:8
EXPOSE 8762
ADD ./target/zuul-gateway-proxy-server-0.0.1-SNAPSHOT.jar zuul-gateway-proxy-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/zuul-gateway-proxy-server-0.0.1-SNAPSHOT.jar"]