FROM openjdk:8
EXPOSE 8100
ADD ./target/price-calculation-service-0.0.1-SNAPSHOT.jar price-calculation-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/price-calculation-service-0.0.1-SNAPSHOT.jar"]