spring:
  application:
    # sets the name in Eureka & Zipkin
    name: product-detail-service
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true

server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/

# No ugly logging pollution, if Eureka isn´t up or found
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF