spring:
  application:
    name: zuul-gateway-proxy-server

server:
  port: 8762

eureka:
  client:
    service-url:
      default-zone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    register-with-eureka: true
    fetch-registry: true

# No ugly logging pollution, if Eureka isn´t up or found
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF